version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ../data/postgres:/var/lib/postgresql/pgdata:rw
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ../data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge
